class ExtensionCategory:
    AZURE = ...
    DEBUGGERS = ...
    EDUCATION = ...
    EXTENSION_PACKS = ...
    FORMATTERS = ...
    KEYMAPS = ...
    LANGUAGE_PACKS = ...
    LINTERS = ...
    MACHINE_LEARNING = ...
    NOTEBOOKS = ...
    OTHER = ...
    PROGRAMMING_LANGUAGES = ...
    SCM_PROVIDERS = ...
    SNIPPETS = ...
    TESTING = ...
    THEMES = ...
    VISUALIZATION = ...


class VSCodeExtension:
    publisher: str
    name: str
    version: str

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...


def get_installed_extensions(
        category: ExtensionCategory = ...
) -> list[VSCodeExtension]: ...


def install_extension(
        extension: str,
        force: bool = ...
) -> None: ...


def uninstall_extension(
        extension: str,
        force: bool = ...
) -> None: ...
